### ISSUE TITLE
Fix Kindle double-covers issue

### ISSUE THREAD

**Issue by nelliemckesson** [macmillanpublishers/bookmaker_addons#58] opened 2016-05-05 17:14 UTC
Kindle displays two covers at the beginning of the book. This likely has something to do with the way they translate the cover.html and cover opf data. This should be fixed in epubmaker_preprocessing or epubmaker_postprocessing.

**Comment by MacmillanWorkflows** [comment] 2016-11-22 19:27
➤ Matthew Retzer commented:
Duplicate of https://github.com/macmillanpublishers/bookmaker/issues/105

**Closed by MacmillanWorkflows** 2016-11-22 19:27 UTC
